USE [master]
GO
/****** Object:  Database [STDTSTSYS_DB]    Script Date: 6/12/2017 10:58:09 AM ******/
CREATE DATABASE [STDTSTSYS_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'STDTSTSYS_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.STDTSTSYS\MSSQL\DATA\STDTSTSYS_DB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'STDTSTSYS_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.STDTSTSYS\MSSQL\DATA\STDTSTSYS_DB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [STDTSTSYS_DB] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [STDTSTSYS_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [STDTSTSYS_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [STDTSTSYS_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [STDTSTSYS_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [STDTSTSYS_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [STDTSTSYS_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [STDTSTSYS_DB] SET  MULTI_USER 
GO
ALTER DATABASE [STDTSTSYS_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [STDTSTSYS_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [STDTSTSYS_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [STDTSTSYS_DB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [STDTSTSYS_DB] SET DELAYED_DURABILITY = DISABLED 
GO
USE [STDTSTSYS_DB]
GO
/****** Object:  Table [dbo].[Questions]    Script Date: 6/12/2017 10:58:09 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Questions](
	[QuestionID] [nchar](14) NULL,
	[QuestionText] [nchar](140) NULL,
	[Answer1Text] [nchar](10) NULL,
	[Answer2Text] [nchar](10) NULL,
	[Answer3Text] [nchar](10) NULL,
	[Answer4Text] [nchar](10) NULL,
	[Difficulty] [int] NULL,
	[SuccessRate] [float] NULL,
	[LastAnswered] [date] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserInfo]    Script Date: 6/12/2017 10:58:09 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserInfo](
	[UserID] [nchar](14) NOT NULL,
	[Username] [nvarchar](14) NOT NULL,
	[Password] [nvarchar](32) NOT NULL,
	[FirstName] [nvarchar](18) NULL,
	[LastName] [nvarchar](18) NULL,
	[Email] [nvarchar](32) NULL
) ON [PRIMARY]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ID Number for Each Question' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'Questions', @level2type=N'COLUMN',@level2name=N'QuestionID'
GO
USE [master]
GO
ALTER DATABASE [STDTSTSYS_DB] SET  READ_WRITE 
GO
